[build]
  # This tells Netlify to run our script before publishing
  command = "npm run build"
  
  # This tells Netlify to publish the compiled files from the 'dist' folder
  publish = "dist"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
