import fs from 'node:fs';
export const site=JSON.parse(fs.readFileSync(new URL('../content/site.json',import.meta.url),'utf8'));
export const projects=JSON.parse(fs.readFileSync(new URL('../content/projects.json',import.meta.url),'utf8'));
export const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export const arrow='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6"/></svg>';
export const icon=type=>{const p={pin:'<path d="M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0"/><circle cx="12" cy="10" r="3"/>',phone:'<path d="M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384"/>',screen:'<rect x="3" y="3" width="18" height="13" rx="2"/><path d="M8 21h8m-4-5v5"/>',chat:'<path d="M20 11.5a8 8 0 0 1-8 8H4l1.5-4A8 8 0 1 1 20 11.5Z"/><path d="M8 9h8m-8 4h5"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',shield:'<path d="m12 2 8 4v6c0 5-8 10-8 10S4 17 4 12V6Z"/><path d="m8 12 3 3 5-6"/>',edit:'<path d="m14 4 6 6M4 20l4-1L21 6a2 2 0 0 0-4-4L4 15Z"/>',check:'<path d="m5 12 4 4L19 6"/>',mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>'};return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${p[type]||p.check}</svg>`;};
export const cta=(label='Get my free preview',href='/free-preview/',cls='')=>`<a class="button ${cls}" href="${href}">${label}${arrow}</a>`;
export const brand=()=>'<a class="brand" href="/">made<span>real</span><small>WEBSITES FOR REAL BUSINESSES</small></a>';
export const header=()=>`<header class="site-header"><div class="wrap header-inner">${brand()}<nav id="main-nav" aria-label="Main navigation"><a href="/work/">Our work</a><a href="/websites/">Websites</a><a href="/pricing/">£35/month</a><a href="/blog/">Journal</a><a href="/about/">About</a><a href="/contact/">Contact</a></nav>${cta('Free preview','/free-preview/','header-cta')}<button class="menu-toggle" aria-controls="main-nav" aria-expanded="false" aria-label="Open menu"><span></span><span></span></button></div></header>`;
export const closing=()=>`<section class="closing wrap" data-reveal><p class="eyebrow">YOUR BUSINESS. MADE REAL.</p><h2>Want to see your<br>website for free?</h2><p>We’ll design your homepage. You decide if you want to go ahead.</p>${cta()}<span class="fine">No card details. No payment for your preview.</span></section>`;
export const footer=()=>`<footer class="site-footer"><div class="wrap footer-grid"><div>${brand()}<p>Independent web design in Lancashire.<br>Real websites. A real person to help.</p><address>${esc(site.street)}, ${esc(site.town)}<br>${esc(site.postcode)}, ${esc(site.region)}</address></div><div><h2>For your business</h2><a href="/websites/trades/">Websites for trades</a><a href="/websites/small-business/">Small business websites</a><a href="/websites/hospitality/">Food & hospitality</a><a href="/google-business-profile/">Google Business Profile help</a><a href="/pricing/">The £35 monthly plan</a></div><div><h2>Around here</h2><a href="/locations/colne/">Web design Colne</a><a href="/locations/burnley/">Web design Burnley</a><a href="/locations/clitheroe/">Web design Clitheroe</a><a href="/locations/lancashire/">Across Lancashire</a><a href="/blog/">The MadeReal journal</a></div><div><h2>Say hello</h2><a href="tel:${site.phoneLink}">${site.phone}</a><a href="mailto:${site.email}">Email MadeReal</a><a href="https://wa.me/447396710347" target="_blank" rel="noopener noreferrer">WhatsApp ${arrow}</a><a href="/free-preview/">Get your free preview</a></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} MadeReal</span><div><a href="/privacy/">Privacy</a><a href="/terms/">Website plan terms</a></div></div></div></footer>`;
export const breadcrumb=(items)=>`<nav class="breadcrumb wrap" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li>${items.map((item,i)=>`<li>${i===items.length-1?`<span aria-current="page">${esc(item.name)}</span>`:`<a href="${item.url}">${esc(item.name)}</a>`}</li>`).join('')}</ol></nav>`;
export function layout({title,description,path='/',body,dark=false,noindex=false,breadcrumbs=[],schema=[],sticky=true}){
const preview=process.env.PREVIEW==='1';const url=site.url+path;
const graph=[{'@type':'Organization','@id':site.url+'/#organization',name:site.name,url:site.url,email:site.email,telephone:site.phoneLink,address:{'@type':'PostalAddress',streetAddress:site.street,addressLocality:site.town,addressRegion:site.region,postalCode:site.postcode,addressCountry:'GB'}},{'@type':'WebSite','@id':site.url+'/#website',url:site.url,name:site.name,publisher:{'@id':site.url+'/#organization'}},{'@type':'WebPage','@id':url+'#webpage',url,name:title,description,isPartOf:{'@id':site.url+'/#website'}}];
if(breadcrumbs.length)graph.push({'@type':'BreadcrumbList',itemListElement:[{name:'Home',url:site.url},...breadcrumbs.map(x=>({name:x.name,url:site.url+x.url}))].map((x,i)=>({'@type':'ListItem',position:i+1,name:x.name,item:x.url}))});
graph.push(...schema);
return `<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${preview||noindex?'noindex, nofollow':'index, follow, max-image-preview:large'}"><link rel="canonical" href="${url}"><meta name="theme-color" content="#090c0b"><meta property="og:type" content="website"><meta property="og:site_name" content="MadeReal"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${url}"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="preload" href="/assets/fonts/space-grotesk-latin-400-700.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/assets/fonts/dm-sans-latin-400-700.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/styles.css"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':graph}).replaceAll('<','\\u003c')}</script><script src="/app.js" defer></script></head><body class="${dark?'dark-top':'light-top'}${sticky?' has-mobile-cta':''}"><a class="skip-link" href="#main">Skip to content</a>${header()}${breadcrumbs.length?breadcrumb(breadcrumbs):''}<main id="main">${body}</main>${footer()}${sticky?`<div class="mobile-cta" role="region" aria-label="Free homepage preview"><span><strong>Preview it free.</strong><small>£35/month if you go ahead.</small></span>${cta('Start my preview')}</div>`:''}</body></html>`;
}
export const intro=(eyebrow,h1,copy)=>`<section class="page-intro wrap"><p class="eyebrow">${eyebrow}</p><h1>${h1}</h1><p class="lead">${copy}</p></section>`;
export const projectImage=(p,{mobile=false,eager=false,classes=''}={})=>`<img class="${classes}" src="/assets/${p.asset}-${mobile?'mobile':'desktop'}.webp" width="${mobile?390:1440}" height="${mobile?844:900}" alt="${esc(p.fullName)} website by MadeReal" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;
export const projectCard=p=>`<article class="project-card" data-sector="${p.sector}" data-reveal><a class="project-image" href="/work/${p.slug}/">${projectImage(p)}<span class="project-open">${arrow}</span></a><div class="project-caption"><div><p>${esc(p.category)}</p><h3><a href="/work/${p.slug}/">${esc(p.name)}</a></h3></div><a class="site-link" href="${p.url}" target="_blank" rel="noopener noreferrer" aria-label="Visit ${esc(p.name)} website">${arrow}</a></div></article>`;
export const workSection=(selection=projects.slice(0,3),heading='Websites we’ve built<br>for local businesses.')=>`<section class="section wrap" id="work"><div class="section-heading" data-reveal><div><p class="eyebrow">OUR WEBSITE WORK</p><h2>${heading}</h2></div><a class="text-link" href="/work/">View all our websites ${arrow}</a></div><div class="project-grid">${selection.map(projectCard).join('')}</div></section>`;
export const processSection=()=>`<section class="process section wrap"><div data-reveal><p class="eyebrow">THE FREE HOMEPAGE PREVIEW</p><h2>See your homepage<br>before you decide.</h2><p class="lead">No deposit. No need to know anything about websites.</p></div><ol><li data-reveal><span>01</span><div><h3>Tell us what you do.</h3><p>Your business name, the work you do and the areas you cover.</p></div></li><li data-reveal><span>02</span><div><h3>See your free design.</h3><p>We send your homepage preview for you to look at on your phone.</p></div></li><li data-reveal><span>03</span><div><h3>Happy? We put it online.</h3><p>£35 a month. We finish your website and keep it up to date.</p></div></li></ol></section>`;
export const benefits=[['screen','Look professional','Your services, photos and work, in a website that’s easy to use on a phone.'],['pin','8 local area pages','Pages for the towns you cover. Working somewhere new? Ask us to add more.'],['mail','A contact form','Let customers ask for a quote straight from your website.'],['phone','Tap to call you','One tap on your phone number makes it easy for customers to get in touch.'],['search','Help with Google','We set up your pages so Google can read what you do and where you work.'],['pin','Google Maps help','We help set up or tidy your Google Business Profile, if your business qualifies.'],['shield','Kept online for you','Hosting and a secure connection included. We handle the setup.'],['chat','Help with changes','New photos, services or opening hours? Just message your designer.']];
export const benefitsSection=()=>`<section class="included section"><div class="wrap"><div class="section-heading" data-reveal><div><p class="eyebrow">WHAT’S INCLUDED</p><h2>What you get for<br>£35 a month.</h2></div><p>All part of your £35 monthly plan.<br>We do the work for you.</p></div><div class="benefit-grid">${benefits.map(([i,h,p])=>`<article data-reveal>${icon(i)}<h3>${h}</h3><p>${p}</p></article>`).join('')}</div></div></section>`;
export const priceBlock=()=>`<section class="price-block wrap" data-reveal><div><p class="eyebrow">YOUR WEBSITE, LOOKED AFTER</p><h2>Your website and<br>ongoing help.</h2><p>Design, hosting, website changes and help with Google. One person to talk to.</p><a class="text-link" href="/pricing/">Everything in the plan ${arrow}</a></div><div class="price-action"><p class="price"><strong>£35</strong><span>/ month</span></p><ul><li>${icon('check')} Free homepage preview first</li><li>${icon('check')} No upfront website build payment</li><li>${icon('check')} Cancel anytime</li></ul>${cta()}<p class="fine">Your website goes offline when your plan ends.</p></div></section>`;
export const questions=[['Is the website really free?','The homepage preview is completely free. If you want us to finish and look after the website, the plan is £35 a month. You do not pay just to see the first design.'],['Can I cancel my monthly plan?','Yes. You can cancel anytime. Your website goes offline when the plan ends. Let us know if you are planning a move so we can explain the next steps before you cancel.'],['How many area pages do I get?','We start with eight pages for the towns and areas you serve. Covering somewhere new? Ask us to add more. Each page should explain the work you actually offer there.'],['Will people find me on Google and Google Maps?','We set up your website so Google can read it, and help with your Google Business Profile if your business is eligible. Google decides which businesses appear and where. No one can promise the top spot.'],['Does the website include a contact form?','Yes. Customers can send you an enquiry through your website, or tap your phone number to call you.'],['Do I need to write everything myself?','No. Tell us what you do, where you work and what customers need to know. We help turn that into clear website copy for you to approve.'],['Will my website work on a phone?','Yes. We build around mobile screens as well as desktop. Text, contact options and navigation should be easy to use whichever device a customer has.'],['Can you guarantee more enquiries?','No one can honestly promise a fixed number. We make the website clear, useful and easy to contact you through. Results also depend on demand, competition, traffic and the service you offer.'],['What about a domain and business email?','We can help with both. If you already own a domain, keep control of it. We confirm any registration, renewal or mailbox charges with you before you decide to go ahead.'],['Can I pay once instead?','Yes. Ask about the £197 one-off website option. It is separate from the £35 managed plan, and we explain the differences before you choose.']];
export const faqSection=(items=questions)=>`<section class="faq section wrap" id="questions"><div data-reveal><p class="eyebrow">A FEW STRAIGHT ANSWERS</p><h2>Good questions.</h2><a class="text-link" href="/contact/">Ask us something ${arrow}</a></div><div>${items.map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div></section>`;
