import fs from 'node:fs';
import {site,esc,arrow,icon,cta,layout,projectFrame,faqSection,closing} from './components.mjs';
const menus=JSON.parse(fs.readFileSync(new URL('../content/hospitality.json',import.meta.url),'utf8'));
const featured=menus[0];
export const hospitalityPage=()=>layout({
 path:'/websites/hospitality/',
 title:'Restaurant & Pub Websites with Editable Menus | MadeReal',
 description:'Websites and online menus for pubs, restaurants and cafés. Log in and update your own dishes and prices. See five real MadeReal menu projects.',
 breadcrumbs:[{name:'Websites',url:'/websites/'},{name:'Food & hospitality',url:'/websites/hospitality/'}],
 schema:[{'@type':'Service',name:'Restaurant and pub websites with self-managed online menus',serviceType:'Hospitality website and online menu design',description:'Websites and online menus with an owner login to update dishes and prices.',provider:{'@id':site.url+'/#organization'},areaServed:{'@type':'Country',name:'United Kingdom'}}],
 body:`<section class="hospitality-hero wrap"><div><p class="eyebrow">WEBSITES FOR PUBS, RESTAURANTS & CAFÉS</p><h1>A menu you can<br><em>change yourself.</em></h1><p class="lead">A proper website for your place. An online menu for your guests. Your own login to keep it up to date.</p>${cta()}<p class="fine">See your homepage for free. We’ll confirm your website and menu setup before you go ahead.</p></div><div class="hospitality-feature"><a class="hospitality-preview" href="${featured.url}" target="_blank" rel="noopener noreferrer">${projectFrame(featured,{eager:true})}</a><div class="hospitality-caption"><div><span class="eyebrow">A REAL MADEREAL MENU</span><h2>${featured.name}</h2></div><a class="text-link" href="${featured.url}" target="_blank" rel="noopener noreferrer">View menu ${arrow}</a></div></div></section>
 <section class="menu-control section"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">YOU’RE IN CONTROL</p><h2>Changed a dish or price?<br>Change it online.</h2></div><p>No need to wait for a designer<br>every time the menu changes.</p></div><ol class="menu-steps">${[['Your own login','Open your menu editor and sign in.'],['Make your changes','Update your dishes, descriptions and prices.'],['Keep guests up to date','Save your menu so customers can see the latest version.']].map(([h,p],i)=>`<li><span>0${i+1}</span><h3>${h}</h3><p>${p}</p></li>`).join('')}</ol></div></section>
 <section class="section wrap hospitality-work"><div class="section-heading"><div><p class="eyebrow">MORE REAL MENU PROJECTS</p><h2>Made for the place.<br>Easy for the guests.</h2></div><p>Open an example and try the menu on your phone.</p></div><div class="hospitality-grid">${menus.slice(1).map(p=>`<article><a class="hospitality-preview" href="${p.url}" target="_blank" rel="noopener noreferrer">${projectFrame(p)}</a><div class="hospitality-caption"><h3><a href="${p.url}" target="_blank" rel="noopener noreferrer">${esc(p.name)} ${arrow}</a></h3></div><p>${p.detail}</p></article>`).join('')}</div><p class="fine hospitality-context">These are real MadeReal online-menu projects, linked to each venue’s existing website. For a food-shop website, take a look at <a href="/work/skipton-cheese/">Skipton Cheese Stall</a>.</p></section>
 <section class="hospitality-included section wrap"><div><p class="eyebrow">MORE THAN A MENU</p><h2>Help people choose.<br>Make visiting easy.</h2></div><div class="hospitality-features">${[['edit','A menu you manage','Log in and update it yourself. We’re here if you need a hand.'],['screen','Easy to read on a phone','Clear dishes, prices and categories. No tiny menu to pinch and zoom.'],['phone','A clear way to book','Link to your booking service, add a booking enquiry form or make your number easy to tap.'],['pin','The details guests need','Your location, opening hours and how to get in touch. Help with an eligible Google Business Profile, too.']].map(([i,h,p])=>`<article>${icon(i)}<h3>${h}</h3><p>${p}</p></article>`).join('')}</div></section>
 ${faqSection([['Can I update the menu myself?','Yes. You get your own login so you can change dishes, descriptions and prices. You do not need to edit website code.'],['Do I need a whole new website?','Not always. An online menu can sit alongside your existing website, like the menu projects shown here. Or we can design a new website and menu together.'],['Can customers book through the website?','We can link to your existing booking service, provide a booking enquiry form or show a tap-to-call number. A new booking or ordering system, and any third-party charges, are agreed separately.'],['Will this help people find us on Google?','We use readable page content, clear business details and useful internal links. We can also help with an eligible Google Business Profile. Google decides where businesses appear; we do not promise a particular position.']])}
 ${closing()}`
});
